name: Commit Now

on:
  workflow_dispatch:
    inputs:
      email:
        description: 'EMail'
        required: true
        default: 'alexaboy430@gmail.com'
      username:
        description: 'Username'
        required: true
        default: 'tfhrigit'
      commit:
        description: 'Commit'
        required: true
        default: 'Penghijauan'
      limit:
        description: 'Limit Commit'
        required: true
        default: '20'
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set Config
        run: |
          EMAIL="${{ github.event.inputs.email }}"
          EMAIL=${EMAIL:-'alexaboy430@gmail.com'}
          USERNAME="${{ github.event.inputs.username }}"
          USERNAME=${USERNAME:-'tfhrigit'}
          git config --local user.email "$EMAIL"
          git config --local user.name "$USERNAME"

      - name: DO It
        run: |
          arr=(
            "chore(bot): 😂 auto commit"
            "chore(bot): 😱 auto commit"
            "chore(bot): 👿 auto commit"
            "chore(bot): 💩 auto commit"
            "chore(bot): 🙏 auto commit"
            "chore(bot): 🙈 auto commit"
            "chore(bot): 🐐 auto commit"
            "chore(bot): 🤖 auto commit"
            "chore(bot): 🟩 auto commit"
            "chore(bot): 👻 auto commit"
          )

          LIMIT="${{ github.event.inputs.limit }}"
          LIMIT=${LIMIT:-20}

          for i in $(seq 1 $LIMIT)
          do
            d="$i-$(date '+%Y-%m-%dT%H:%M:%SZ')"
            echo $d > LAST_UPDATED
            git add -A
            rand=$((RANDOM % ${#arr[@]}))
            git commit -m "${arr[$rand]}"
          done

      - name: GitHub Push
        uses: ad-m/github-push-action@master
        with:
          force: true
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
